name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Rin golangci-lint
        uses: actions-contrib/golangci-lint@v1
